-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE pr_index (
  pr_page_id INT NOT NULL,
  pr_count INT DEFAULT 0,
  pr_q0 INT DEFAULT 0,
  pr_q1 INT DEFAULT 0,
  pr_q2 INT DEFAULT 0,
  pr_q3 INT DEFAULT 0,
  pr_q4 INT DEFAULT 0,
  PRIMARY KEY(pr_page_id)
);
